import type { Metadata } from "next";
import "./globals.css";
import { Mulish } from "next/font/google";
import localFont from "next/font/local";

const mulish = Mulish({
  subsets: ["latin"],
});

const engravers = localFont({ src: "./assets/font/engravers-regular.otf" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${engravers.className} antialiased scroll-smooth`}>
        {children}
      </body>
    </html>
  );
}
